### ISSUE TITLE
[SERVER]Большое количество ошибок после разрыва соединения

### ISSUE THREAD

**Issue by anry-das** [group52/TaskManager#10]
На сервере после разрыва соединения клиентом постоянно сыпятся ошибки:
```
2018-04-04 14:12:17 ERROR Server:82 - InputOutput exception: 
java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:154)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	at java.io.InputStreamReader.read(InputStreamReader.java:184)
	at java.io.BufferedReader.fill(BufferedReader.java:161)
	at java.io.BufferedReader.readLine(BufferedReader.java:324)
	at java.io.BufferedReader.readLine(BufferedReader.java:389)
	at controller.Server.recieveFile(Server.java:78)
	at controller.Server.run(Server.java:40)
```

**Comment by group52** [comment]
fcdc445
