### ISSUE TITLE
[CLIENT]NullPointerException при изменении списка задач

### ISSUE THREAD

**Issue by anry-das** [group52/TaskManager#16]
При выборе в списке задач изменения/удаления задачи получаем сообщение **NullPointerException**
```
java.lang.NullPointerException
	at com.group52.client.actions.Handler$Listener.actionPerformed(Handler.java:269)
	at javax.swing.JComboBox.fireActionEvent(JComboBox.java:1258)
	at javax.swing.JComboBox.contentsChanged(JComboBox.java:1332)
	at javax.swing.JComboBox.intervalRemoved(JComboBox.java:1352)
```

**Comment by group52** [comment]
release 93
